#Variabel dan Tipe Data

#Sub Bab Variabel

In [ ]:
a="mangga, apel,rambutan"

In [ ]:
a-2=mangga

#Tipe Data

5 Tipe data, yaitu:
  1. Integer atau bilangan bulat
  2. Float atau bilangan desimal
  3. String atau kalimat
  4. Boolean yang terdiri dari True and False
  5. Complex yang merupakan bilangan kompleks
  

In [ ]:
# membuat variabel
kalimat ='ini adalah variabel'
bilangan1 = 4
bilangan2 = 2.5
bilangan3 = True
bilangan4 = 1j + 4

In [ ]:
# menampilkan tipe data
print(type(kalimat))
print(type(bilangan1))
print(type(bilangan2))
print(type(bilangan3))
print(type(bilangan4))


<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'complex'>


#Latihan 1

In [ ]:
# buatlah 5 variable kalian sendiri dengan 5 macam tipe data
# lalu tampilkan variable menggunakan fungsi print

In [ ]:
# membuat variable
kalimat = 'ini adalah variabel'
bilangan1 = 3
bilangan2 = 1.5
bilangan3 = True
bilangan4 = 7j + 3

In [ ]:
# menampilkan tipe data
print(type(kalimat))
print(type(bilangan1))
print(type(bilangan2))
print(type(bilangan3))
print(type(bilangan4))


<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'complex'>


#List

List adalah jenis kumpulan data terurut (ordered sequence), dan merupakan salah satu variabel yang sering digunakan pada Phyton. serupa, namun tidak sama dengan array pada pemrograman lainnya. Bedanya, elemen List pada Phyton tidak harus memiliki tipe data yang sama. List cukup mudah digunakan yaitu dengan menggunakan kurung siku dan dan elemen yang dipisahkan dengan koma.

Setiap data di dalamnya dapat diakses dengan indeks yang dimulai dari 0.

In [ ]:
#Contoh List
L1 = [1,4,2,13]



In [ ]:
matkul = ["furry", "pdp", "metnum", "graph"]
print(matkul[2])
print(matkul[2:])
print(matkul[1:3])
print(matkul[-2])
print(matkul[-3:-1])

metnum
['metnum', 'graph']
['pdp', 'metnum']
metnum
['pdp', 'metnum']


In [ ]:
print(matkul[-1])

graph


#Latihan 1

In [ ]:
#buatlah list kalian sendiri dengan tiga tipe data minimal enam elemen

In [ ]:
#List
S1 = [1,3,5,15]

In [ ]:
hewan = ["kucing", "kelinci", "panda", "singa"]
print(hewan[2])
print(hewan[2:])
print(hewan[1:3])
print(hewan[-2])
print(hewan[-3:-1])
print(hewan[-4:1])

panda
['panda', 'singa']
['kelinci', 'panda']
panda
['kelinci', 'panda']
['kucing']


# Sifat-sifat List

In [ ]:
L1 = [1,4,2,13]
L1

[1, 4, 2, 13]

In [ ]:
#Terurut/ordered
print("memanggil List L1 dengan Indeks urutan :", L1[0:3])

memanggil List L1 dengan Indeks urutan : [1, 4, 2]


In [ ]:
#Bisa diganti/mutable
L1[1] = 2
print(L1)

[1, 2, 2, 13]


In [ ]:
matkul = ["furry", "pdp", "metnum", "graph", "sisdim"]
matkul[3] = "aktuaria"
print(matkul)

['furry', 'pdp', 'metnum', 'aktuaria', 'sisdim']


In [ ]:
#Dapat diindeks/slicing
L1 = [1, "dua", True, 2+3J]
print("slicing List L1 :", L1[3])

slicing List L1 : (2+3j)


In [ ]:
#Dapat diijinkan duplikasi
L1 = [1, "dua", True, 2+3j, 2+3j]
print("Duplikat pada list L1", L1)

Duplikat pada list L1 [1, 'dua', True, (2+3j), (2+3j)]


# Latihan 2

In [ ]:
#Ganti elemen yang ada pada list yang kalian buat

In [ ]:
#Sifat-siat list

#Terurut/ordered
print("Memanggil List L1 dengan indeks urutan :", L1[0:2])

Memanggil List L1 dengan indeks urutan : [1, 'dua']


# Struktur Data Tuple



Tuple adalah jenis dari struktur data yang tidak dapat diubah elemennya. Umumnya tuple digunakan untuk data yang bersifat sekali tulis, dan dapat dieksekusi lebih cepat. Tuple didefinisikan dengan kurung dan elemen yang dipisahkan dengan koma.



In [ ]:
#Contoh tuple
T1 = (1, 'dua', True, 1+2j)
print("ini adalah tuple", T1)

ini adalah tuple (1, 'dua', True, (1+2j))


In [ ]:
#Menampilkan tipe struktur data
type(T1)

tuple

# Latihan

In [ ]:
#buatlah list kalian sendiri dengan tiga tipe data minimal enam elemen

In [ ]:
T2 = ("desimal", 76.0, 3+10j)
print("ini adalah tuple dua", T2)

ini adalah tuple dua ('desimal', 76.0, (3+10j))


In [ ]:
L3 = [2.5, 12, 250, 17.8]
print(type(L3))

<class 'list'>


In [ ]:
L4 = ["bilangan desimal", 2.5, 17.8, "bilangan bulat", 12, 250]
L4

['bilangan desimal', 2.5, 17.8, 'bilangan bulat', 12, 250]

In [ ]:
print(L3)
print(L4)

[2.5, 12, 250, 17.8]
['bilangan desimal', 2.5, 17.8, 'bilangan bulat', 12, 250]


# Sifat-Sifat Tuple

In [ ]:
#Terurut/ordered
T1[0:3]

(1, 'dua', True)

In [ ]:
#Tidak bisa diganti/imutable
T1[2] = "manusia"

In [ ]:
#Dapat diindeks/slicing
print("elemen kedua dari tuple T1 adalah :", T1[1])

elemen kedua dari tuple T1 adalah : dua


In [ ]:
#Dapat diijinkan duplikasi
T2 = (3, 2.4, True, 2.4)
T2

(3, 2.4, True, 2.4)

# Menggabungkan Tuple

In [ ]:
#Menggabungkan Tuple
T3 = T1 + T2
T3

(1, 'dua', True, (1+2j), 3, 2.4, True, 2.4)

# Latihan 2

In [ ]:
#Buatlah tuple lalu gabungkan 2 tuple yang telah kamu buat

In [ ]:
T3 = ("ganjil", 21, True, 1+4j)
print("ini adalah tuple tiga", T3)

ini adalah tuple tiga ('ganjil', 21, True, (1+4j))


In [ ]:
#gabungkan T2 dan T3
T4 = T2 + T3
T4

(3, 2.4, True, 2.4, 'ganjil', 21, True, (1+4j))

# String

In [ ]:
#Slicing pada string
A = "Belajar Struktur data string"
print(A[:5])
print(A[3:])
print(A[-5:])
print(A[4:9])

Belaj
ajar Struktur data string
tring
jar S


In [ ]:
print(A[8:16])


Struktur
Struktu


# Latihan

In [ ]:
#Buatlah variable string lalu lakukan slicing dengan menghilangkan karakter pertama dan terakhir

In [ ]:
A = "Belajar Struktur data string"
print(A[1:27])

elajar Struktur data strin


# Memodifikasi String

In [ ]:
#upper()
A. upper()

'BELAJAR STRUKTUR DATA STRING'

In [ ]:
#lower()
A. lower ()

'belajar struktur data string'

In [ ]:
#replace()
A. replace('l', 'd')

'Bedajar Struktur data string'

In [ ]:
#replace()
A. replace('u', 'i')

'Belajar Striktir data string'

In [ ]:
#split()
A.split()

['Belajar', 'Struktur', 'data', 'string']

# Menggabungkan String

In [ ]:
A = "Belajar Struktur data string"
B = "Pejuang Data 3.0"
A + " " + B

'Belajar Struktur data string Pejuang Data 3.0'

# Set

Set adlah kumpulan item bersifat unik dan tanpa urutan

In [ ]:
#Contoh Set
S1 = {1, "dua", True, 2+3j}

In [ ]:
#Sifat-sifat set

#Tidak Terurut/unordered
print("Memanggil Set S1 dengan indeks urutan")

Memanggil Set S1 dengan indeks urutan


In [ ]:
S1 = {1, "dua", True, 2+3j}
#Tidak dapat diindeks
print("Slicing set 1", S1[3])

In [ ]:
#Dapat diijinkan duplikasi
S1 = {1, "dua", "dua", 2, 2+3j} #Boolean tidak terbaca atau dianggap tidak ada
print("duplikasi pada set 1:", S1)

duplikasi pada set 1: {1, 'dua', 2, (2+3j)}


In [ ]:
ganjil={1,3,5,7,9}
genap={2,4,6,8,10}
prima={2,3,5,7}

# Union
print(ganjil.union(genap))

#Intersection
print(ganjil.intersection(prima))

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{3, 5, 7}


# Dictionary

In [ ]:
L1 = [1, 'dua', True, 2+3j, 2+3j]
L1

[1, 'dua', True, (2+3j), (2+3j)]

In [ ]:
#Buatlah Struktur data dictionary kalian sendiri

In [ ]:
#Contoh dictionary
L2 = [3, 'tiga', False, 2000, 7.8]
L2

[3, 'tiga', False, 2000, 7.8]

In [ ]:
D1 = {5: 'ganjil', 2+2j : 8, 2.5 : True, 'list':L1}
      print(D1)

In [ ]:
D2 = {10: 'genap', 3+3j : 8, 5.5 : True,'list':L2}
print(D2)

{10: 'genap', (3+3j): 8, 5.5: True, 'list': [3, 'tiga', False, 2000, 7.8]}


In [ ]:
L2[2]

False

In [ ]:
#memanggil elemen berdasarkan key
print("D1[5] = ", D1[5])
print("D1[2+2j] = ", D1[2+2j])
print("D1[2.5] = ", D1[2.5])

In [ ]:
#memanggil elemen berdasarkan key
print("D1['key'] =", D1['key']) ;

# Latihan 2

In [ ]:
#memanggil elemen berdasarkan key
print("D2[10] = ", D2[10]) 
print("D2[3+3j] = ", D2[3+3j]) 
print("D2[5.5] = ", D2[5.5])

D2[10] =  genap
D2[3+3j] =  8
D2[5.5] =  True


In [ ]:
#memanggil elemen berdasarkan value
print("D2['genap'] = ", D2['genap'])
print("D2['8'] = ", D2['8'])
print("D2['True'] = ", D2['True'])

# Percabangan/Struktur Pemilihan

Pada bagian ini, kamu akan membuat keputusan pada bahasa pemrograman Python menggunakan struktur percabangan atau sering disebut IF ELSE Statment. Pengembalian keputusan dibutuhkan ketika kamuakan mengeksekusi suat kode jika sebuah kondisi tertentu dipenuhi.
Statment if...elif...else digunakan pada bahasa Python untuk pengambilan keputusan.

# Example Phyton IF Statment

In [ ]:
angka = -2
if angka > 0:
  print(angka, "adalah bilangan positif.")
print(angka, "adalah bilangan negatif.")

-2 adalah bilangan negatif.


In [ ]:
#Jika angka adalah bilangan positif maka print "adalah bilangan positif"

angka = -1

In [ ]:
if test expression:
  Body of if
  else:
    Body of else

In [ ]:
#Program disusun untuk mengecek apakah 

angka = 3

if angka >= 0:
  print("Bilangan lebih dari atau samadengan 0")
else:
  print("Bilangan kurang dari 0")

Bilangan lebih dari atau samadengan 0


In [ ]:
angka = 7

if angka >= 0:
  print("Bilangan lebih dari atau samadengan 0")
else:
  print("Bilangan kurang dari 0")

Bilangan lebih dari atau samadengan 0


In [ ]:
a = 5
b = 5

if a==b:
  print("a dan b bernilai sama")
else:
  print("a dan b bernilai berbeda")

a dan b bernilai sama


In [ ]:
#membaca dua angka
bil1 = int(input("Masukkan bilangan pertama"))
bil2 = int(input("Masukkan bilangan kedua"))

#Memilih blangan yang lebih besar
if bil1 > bil2:
  bil_lebih_besar = bil1
else:
  bil_lebih_besar = bil2

#Menampilkan hasil
print("Bilangan yang lebih besar adalah:", bil_lebih_besar)

Masukkan bilangan pertama7
Masukkan bilangan kedua8
Bilangan yang lebih besar adalah: 8


# IF ELIF ELSE Statments

In [ ]:
if test expression:
  Body of if
elif test expression:
  Body of elif
else:
  Bod of else

# Argumen

Fungsi dapat memiliki argumen default dengan nilai yang telah ditentukansebelumnya. Argumen ini dapat ditinggalkan dan nilai default kemudian diteruskan ke fungsi, atau argumen dapat dirubah dengan nilai yang berbeda. Perhatikan bahwa argumen default harus ditentukan sebagai parameter terakhir dalam suatu fungsi.

In [ ]:
#Argumen default
def angka2(a, b, c, d=4):
    print(a, b, c, d)

angka2(1, 2, 3, 4)
angka2(1, b=2, c=3, d=100)
angka2(1,2,3)


#Argumen default harus diletakkan terakhir

1 2 3 4
1 2 3 100
1 2 3 4


#Parameter

- Parameter adalah variable yang digunakan dalam deklarasi fungsi
- Argumen adlah nilai yang diberikan saat pemanggilan fungsi

In [51]:
def data_nama(nama): #'nama' adalah parameter karena terletak di dalam fungsi
    print(nama)
    
data_nama('Dhea') #'Dhea' adalah argumen

Dhea


#Argumen Posisi dan Argumen Kata Kunci

Kita bisa menyatakan argumen posisi atau argumen kata kunci. Beberapa manfaat argumen kata kunci dapat berupa:
- Kita dapat menyebut arumen dengan mereka (a,b,c) untuk pemperjelas apa yang merekan wakili
- Kita dapat mengatur ulaang argumen denga cara mrmbuatnya paling mudah dibaca

In [ ]:
def angka(a, b, c):
  print(a, b, c)

#Argumen posisi
#argumen berdasarkan posisi
angka(1, 2, 3)

#argumen berdasarkan kata kuncinya
angka(a=1, b=2, c=3)
angka(c=3, b=2, a=1)
#catatan jika sudah diberi kunci maka urutan tidak menjadi penting

#campuran antara argjmen posisi dan argumen kata kunci
angka(1, b=2, c=3)

#ini tidak diijinkan:
#foo(1, b=2, 3) #argumen posisional setelah argumen kunci
#foo(1, b=2, a=3) #terdapat dua nilai untuk argumen kunci 'a'

1 2 3
1 2 3
1 2 3
1 2 3


# Praktik Membuat Fungsi

In [ ]:
x = 1
y = 2
x+y

3

In [ ]:
def penjumlahan(x,y): #input
  a=x+y               #proses
  return a           #output

  penjumlahan(1, 2)   #menggunakan fungsi

Penjumlahan yang memungkinkan untuk tiga bilangan

In [ ]:
def penjumlahan(x,y,z=None):
  if (z==None):
      return x+y
  else:
      return x+y+z

print(penjumlahan(1, 2))
print(penjumlahan(1, 2, 3))

3
6


menyimpan hasil fungsi dalam variabel

In [ ]:
def penjumlahan(x,y):
    return x+y

a = penjumlahan
a(1, 2)

3

# Penjumlahan yang memungkinkan untuk tiga bilangan

In [ ]:
def penjumlahan(x,y,z=None)
    if (Z==None):
          return x+y
    else:
          return x+y+z

print(penjumlahan(1, 2))
print(penjumlahan(1, 2, 3))

In [ ]:
def penjumlahan(x,y):
    return x+y

a = penjumlahan
a(1, 2)

3

# Lambda

Fungsi Lambda adlah fungsi yang didefinisikan tanpa nama. Fungsi lambda dapat mengambil sejumlah arguments, tetapi hanya dapat memiliki satu expression. sementara fungsi normal dapat didefinisikan menggunakan kata kunci def, dalam Python fungsi anonym didefinisikan menggunakan kata kunci lambda.

Fungsi Lambda digunakan ketika fungsi sederhana hanya digunakan seKali atauuntuk waktu yang singkatdalam kode kita. Penggunaaanya yang paling umum adalah sebagai argumen untuk fungsi tingkat tinggi(fungsi yang menggunakn fungsi lain sebagia argumen).

Lambda expression di Python adalah sebuah ekspresi untuk membuat fungsi.

Lambda sendiri berasal dari teori kalkulus, yakni Lambda Calculus yang dikenalkan oleh Alonzo Church di tahun 1930.

Berkat lambda, kita bisa membuat fungsi tanpa nama atau dikenal juga dengan anonymous fungction.


Misalkan kita punya fungsi penjumlahan kuadrat seperti ini:

In [ ]:
def suqare_sum(x,y):
  return x**2 + y**2

dengan lambda kita tidak perlu menggunakan def dan return, bahkan kita juga tidak perlu menuliskan namanya.

In [ ]:
lambda x,y : x**2 + y**2

<function __main__.<lambda>(x, y)>

# Menggunakan Lambda Expression

In [ ]:
greeting = lambda name: print(f"hello, {name}")

In [ ]:
greeting("Dian")
greeting("Ayu")

In [ ]:
#Fungsi Lambda untuk menambahkan angka 10 kepada argumen input
f = lambda x: x+10
val1 = f(5)
val2 = f(100)
print(val1,val2)

15 110


In [ ]:
#Fungsi Lambda untuk mengalikan dua argumen input dan menampilkan dua argumen input dan menampilkan hasilnya
f = lambda x,y:x*y
val3 = f(2,10)
val4 = f(7,5)
print(val3,val4)

20 35


#Function

Function (fungsi) adalash sebuah blok statment yang hanya akan dijalankan saat ia panggil.

In [ ]:
def nama_fungsi(argument):
  statment_1
  -
  statment_n
  return returned_value

- nama fungsi adalah untuk fungsi yang anda definisikan, memiliki aturan seperti penamaan variable
- argumen adalah variable masukan ke fungsi, biasa tanpa ariabel, satu variable atau lebih
- statment_1_statment_n adlah algoritma yang telah anda tranfer dalam bahasa python yang merupakan inti dari seluruh statment adlah menjorok (indent) ke dala seperti yang pernah anda pelajari dari conditioning dan looping
- return_value adalah variabel output dan fungsi anda, bisa tanpa variable, satu variabel atau lebih

# Anonymous Function

In [44]:
def say_hello(Dhea):
  print(f"hello{Dhea}, apa kabar?")

  ucapin = say_hello(Dhea)

# Eksekusi Lambda secara Langsung

In [ ]:
(lambda x,y: x**2 + y**2)(4,6)

52

# Mengapa Harus Pakai Lambda

In [ ]:
bilangan = [10,2,8,7,5,4,3,11,0,1]
filtered_result = map (lambda x: x*x, bilangan)
print(list(filtered_result))

[100, 4, 64, 49, 25, 16, 9, 121, 0, 1]


In [ ]:
#Menentukan bilangan genap
genap = lambda x: x%2 == 0
list(filter(genap, range(11)))

[0, 2, 4, 6, 8, 10]

# DataFrame

In [20]:
import pandas as pd

Membuat Data Frame Menggunakan List dan Fungsi Zip

In [43]:
# List Buah (string)
list_buah = ['Naga', 'Durian', 'Mangga', 'Rambutan', 'Anggur', 'Semangka', 'Manggis']

# List Berat Buah (Integer)
list_berat = [50, 800, 150, 10, 2, 300, 70]

# Membuat dataframe menggunakan Dua Nuah List dengan Fungsi Zip
df = pd.DataFrame(list(zip(list_buah, list_berat)),
                  columns = ['nama buah','berat buah'])
df

nama buah  berat buah
0      Naga          50
1    Durian         800
2    Mangga         150
3  Rambutan          10
4    Anggur           2
5  Semangka         300
6   Manggis          70

Membuat DataFrame Menggunakan List Multidimensi

In [41]:
# List Multidimensi (Nama, Usia)
lst = [['Killua', 19], ['Muichiro', 18],
       ['Hiroto', 20], ['Chinen', 16]]

df = pd.DataFrame(lst, columns =['Nama', 'Usia'])
df

Nama  Usia
0    Killua    19
1  Muichiro    18
2    Hiroto    20
3    Chinen    16

Membuat dataframe menggunakan dictionary

In [ ]:
mobil = {'Type Mobil': ['Honda Civic', 'Toyota Corolla', 'Ford Focus', 'Audi A4'],
         'Harga(USD)': [22000,25000,27000,35000]
         }
df = pd.DataFrame(mobil)

df

Type Mobil  Harga(USD)
0     Honda Civic       22000
1  Toyota Corolla       25000
2      Ford Focus       27000
3         Audi A4       35000

#Membuat Data Frame

Membuat Matriks Menggunakan List

In [18]:
import pandas as pd

In [42]:
# List
list_buah = ['Naga', 'Durian', 'Mangga', 'Rambutan', 'Anggur', 'Semangka', 'Manggis']

# Membuat dataframe menggunakan list_buah
df = pd.DataFrame(list_buah)
df

0
0      Naga
1    Durian
2    Mangga
3  Rambutan
4    Anggur
5  Semangka
6   Manggis

#Import DataFrame dari File CSV

In [ ]:
df_super_store = pd.read_csv('/content/Super-Store-Dataset.csv')
df_super_store.head()

# Import DataFrame dari Excel

In [ ]:
df_pilkada=pd.read_excel('/content/datasetpilkadadki.xlsx')
df_pilkada.head()

# NumPy Array

Membuat Array NumPy kita bisa membuat array menggunakan NumPy dengan membungkusnya terlebih dahulu du list dan dirubah menjadi numpy array

In [24]:
import numpy as np

In [ ]:
list_1 = [1,2,3,4,5]
arr_1 = np.array([list_1])
arr_1

array([[1, 2, 3, 4, 5]])

In [ ]:
print(np.zeros((2,5))) # membuat array dangan nilai 0 dengan shape (5,5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.ones((5,3))) # membuat array dengan nilai 1 dengan shape (5,5)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
print(np.arange(1, 10, 2)) # arrange(start, stop, step)

[1 3 5 7 9]


In [27]:
print(np.linspace(1, 10, 2)) #linspace(start, stop, number)

[ 1. 10.]


In [29]:
print(np.logspace(1, 10, 2)) #logspace(start,stop,number)

[1.e+01 1.e+10]


In [28]:
print(np.full((2,2), 4)) #membuat array matriks dengan shape (2,2)

[[4 4]
 [4 4]]


In [34]:
A = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A, 3)) #membuat array matriks dengan shape yang sama dengan A dengan semua elemennya


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [ ]:
print(np.random.rand(4,2)) # Random decimal numbers

[[0.87812872 0.16359164]
 [0.88543623 0.12972127]
 [0.1151584  0.69951599]
 [0.6064261  0.02821672]]


In [ ]:
print(np.random.randint(-4,8, size=(3,3))) # Random Integer values

[[-2 -3  7]
 [ 6  5  7]
 [ 6  5  7]]


In [ ]:
print(np.identity(5)) # Membuat matriks identitas

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1,2,3]]) # Membuat matriks dengan perulangan array
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#Membuat Array NumPy

Kita bisa membuat Array menggunakan NumPy dengan membungkusnya terlebih dahulu di List dan dirubah menjadi numpy array

In [35]:
list_1 = [1,2,3,4,5]
arr_1 = np.array([list_1])
arr_1

array([[1, 2, 3, 4, 5]])

#Beberapa fungsi yang dapat digunakan dalam membuat array

zeros()    -> Membuat array dengan nilai 0

ones()     -> Membuat array dengan nilal 1

arange()   -> Membuat array dengan nilai dalam range

Linspace() -> Membuat array dengan nilai dalan interval

logspace() -> Membuat array dengan nilai log Base10 dalam Interval

full       -> Membuat array dengan semua elemen penyusunnya sama

full like  -> Membuat array dengan semua elemen penyusunnya sana namun ukurannya dari array lainnya

Identity   -> Membuat array matriks identitas

repeat     -> Membuat array dengan perulangan array atau sequence

# Multidimensional Array

Salah satu fitur menarik dari NumPy adalah dia mampu membuat multidimensional array yang melakukan manupulasi array dengan mudah dan cepat


Multidimentional array adalah array berbentuk lebih dari 1 dimensi (1D), bisa 2D, 3D, 4D dan seterusnya


Cara membuat multidimentional array sama dengan membuat array 1 dimensi, perbedaannya hanya pada parameter yang digunakan


Berikut contohnya membuat array 2 dimensi

In [ ]:
arr_2 = np.array([(1,2,3,4,5), (2.4.6.8.10)])
arr_2

# Metode-metode pada Array

In [ ]:
a=np.array([29, 28,30], dtype='int32')

# Indexing dan Slicing

Kita juga dapat melakukan indexing dan slicing terhadap array dengan mudah 

Indexing dimulai dari 0 dan dimulai dengan notasi bracket "[ ]"

Misal kita ingin mencari nilai yang berada di index 0,2, dan 4

In [38]:
arr_3 = np.array([1,2,3,4,5])
print(arr_3[0])
print(arr_3[2])
print(arr_3[4])

1
3
5


# Operasi Aritmatika

Kita bisa menggunakan operasi aritmatika seperti penjumlahan, pengurangan, perkalian, pembagian, dan perpangkatan

Operator yang digunakan adalah +,-,./dan*

Berikut contoh operasi aritmatika pada array